force-app/main/default/objects/Account/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <displayFormat>{0000000000}</displayFormat>
    <label>Customer ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <label>Customer ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/isNew__c.field-meta.xml
<CustomField>
    <fullName>isNew__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isNew</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offer</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>WEB</fullName>
            </value>
            <value>
                <fullName>AEM</fullName>
            </value>
            <value>
                <fullName>Optimus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Lead_Sub_Status__c</fullName>
    <label>Lead Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer dropped</fullName>
            </value>
            <value>
                <fullName>Queue</fullName>
            </value>
            <value>
                <fullName>Follow Up</fullName>
            </value>
            <value>
                <fullName>Logged In</fullName>
            </value>
            <value>
                <fullName>New Query</fullName>
            </value>
            <value>
                <fullName>QDE Pending</fullName>
            </value>
            <value>
                <fullName>Offer generated</fullName>
            </value>
            <value>
                <fullName>VKYC Initiation Pending</fullName>
            </value>
            <value>
                <fullName>VKYC Initiated</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>DDE Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Offer_ID__c.field-meta.xml
<CustomField>
    <fullName>Offer_ID__c</fullName>
    <label>Offer ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Segment_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saving Account</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Segment_Type__c.field-meta.xml
<CustomField>
    <fullName>Segment_Type__c</fullName>
    <label>Segment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Offer</label>
    <nameField>
        <displayFormat>OFF-{00000000}</displayFormat>
        <label>Offer id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Offer_Status__c.field-meta.xml
<CustomField>
    <fullName>Offer_Status__c</fullName>
    <label>Offer Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Offer Converted</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>SEPL</fullName>
            </value>
            <value>
                <fullName>Home Loan</fullName>
            </value>
            <value>
                <fullName>Personal Loan</fullName>
            </value>
            <value>
                <fullName>LAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeadDropOffBatch.cls
/**
* @File Name : LeadDropOffBatch.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : October 20, 2024
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | October 20, 2024 |   | Initial Version
**/

global class LeadDropOffBatch implements Database.Batchable<sObject>{

	Set<Lead> leadlist=new Set<Lead>();
	List<Lead> updateLead=new List<Lead>();

	List<String> leadstatus=new String[]{'Contact Center','New'};
	List<String> leadoffer=new String[]{'Active','In Progress'};

	String strcc='Credit Card';
	String strsource='Internet';

	List<String> lead2hDrop=system.label.DropIn2hCampaignList.split(',');
	List<String> lead4hDrop=system.label.DropIn4hCampaignList.split(',');
	
	global Database.QueryLocator start(Database.BatchableContext bc){

		return Database.getQueryLocator('Select id,Status, Lead_Sub_Status__c, LastModifiedDate, Customer_ID__c, Offer_ID__c, Campaign__r.Name, Campaign__c,isNew__c from Lead'
		                                +' where Customer_ID__c != null And Segment_Type__c =:strcc And Lead_Source__c =:strsource'
										+' And (Offer_ID__c !=null and Status In:leadstatus) And (Campaign__r.Name In:lead2hDrop or Campaign__r.Name In:lead4hDrop)');
	}

	global void execute(Database.BatchableContext bc,List<Lead> llist){
		System.debug('This is list 2h campaign'+lead2hDrop);
		System.debug('This 4h camp'+lead4hDrop);
		System.debug('Hello I am execute');
		long longlastmodifiedDate;
		long longNowTime=Datetime.now().getTime();
		long longmiliseconddiff;
		long longminutediff;
		System.debug(longNowTime);
		System.debug('List of lead info'+llist);

		List<String> setofferdetail=new List<String>();
		List<String> setActiveofferdetail=new List<String>();

		for(Lead led:llist){
			setofferdetail.add(led.Offer_ID__c);
		}

		List<Offer__c> lstofferdetail=new List<Offer__c>();

		lstofferdetail=[select Name from Offer__c where Product__c ='Credit Card' and Offer_Status__c In:leadoffer and Name In:setofferdetail];
		System.debug('List of offer'+lstofferdetail);

		for(Offer__c offlist:lstofferdetail){
			setActiveofferdetail.add(offlist.Name);
		}
		System.debug('List of active offer'+setActiveofferdetail);

		Set<Lead> setofupdatelist=new Set<Lead>();

		for(Lead lrec:llist){
			longlastmodifiedDate=lrec.LastModifiedDate.getTime();
			longmiliseconddiff=longNowTime-longlastmodifiedDate;
			longminutediff=longmiliseconddiff/60000;
			System.debug('Longminute'+longminutediff);

			if(lrec.Campaign__c!=null && longminutediff>Long.valueOf(System.label.Drop2hCampaignTime) && lead2hDrop.contains(lrec.Campaign__r.Name)){
				setofupdatelist.add(lrec);
			}else if(lrec.Campaign__c!=null && longminutediff>Long.valueOf(System.label.Drop4hCampaignTime) && lead4hDrop.contains(lrec.Campaign__r.Name)){
				setofupdatelist.add(lrec);
			}
		}

		List<Lead> setupdateLead=new List<Lead>();

		if(setofupdatelist.size()>0){
			for(Lead setUpdate : setofupdatelist){
				setUpdate.Status='Contact Center';
				setUpdate.Lead_Sub_Status__c='Customer dropped';
				setUpdate.isNew__c=false;
				setupdateLead.add(setUpdate);
			}
		}
		System.debug('List of lead to be update'+setupdateLead);

		Database.SaveResult[] leaddrop = Database.update(setupdateLead, false);

		for(Database.SaveResult le:leaddrop){
			if(le.isSuccess()){
				System.debug('Successfully updated the lead'+le.getId());
			}else{
				for(Database.Error err : le.getErrors()) {
                    System.debug('The following error has occurred.');                    
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('Account fields that affected this error: ' + err.getFields());
                }
			}
		}

	}

	global void finish(Database.BatchableContext bc){
		System.debug('Hello i am Finish');
	}

}