force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Offer</label>
    <nameField>
        <displayFormat>OFF-{00000000}</displayFormat>
        <label>Offer id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/fields/Card_benefits_offered__c.field-meta.xml
<CustomField>
    <fullName>Card_benefits_offered__c</fullName>
    <label>Card benefits offered</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/External_Offer_ID__c.field-meta.xml
<CustomField>
    <fullName>External_Offer_ID__c</fullName>
    <label>External Offer ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Max_Offer_Amount__c.field-meta.xml
<CustomField>
    <fullName>Max_Offer_Amount__c</fullName>
    <label>Max Offer Amount</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Max_ROI__c.field-meta.xml
<CustomField>
    <fullName>Max_ROI__c</fullName>
    <label>Max ROI</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Min_Offer_Amount__c.field-meta.xml
<CustomField>
    <fullName>Min_Offer_Amount__c</fullName>
    <label>Min Offer Amount</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Min_ROI__c.field-meta.xml
<CustomField>
    <fullName>Min_ROI__c</fullName>
    <label>Min ROI</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Offer_Status__c.field-meta.xml
<CustomField>
    <fullName>Offer_Status__c</fullName>
    <label>Offer Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Offer Converted</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Offered_Card_Best_Fit__c.field-meta.xml
<CustomField>
    <fullName>Offered_Card_Best_Fit__c</fullName>
    <label>Offered Card(Best Fit)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Used Car</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Assets</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/offerRecordGetter.cls
/**
* @File Name : offerRecordGetter.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : October 6, 2024
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | October 6, 2024 |   | Initial Version
**/

public class offerRecordGetter {

    @AuraEnabled(cacheable=true)
    public static List<Offer__c> findById(String recordId){
      System.debug(recordId);
      List<Offer__c> offerrecord=[Select id,Offer_Status__c,External_Offer_ID__c,Max_Offer_Amount__c, Min_Offer_Amount__c, Max_ROI__c, Min_ROI__c,Card_benefits_offered__c,Offered_Card_Best_Fit__c,Product_Category__c from Offer__c where Id=:recordId];
      return offerrecord;
    }

    @AuraEnabled(cacheable=true)
    public static String getCustomLabel(String labelName) {
          try {
              String value=System.Label.get('',labelName,'en');
              return value;
          } catch (Exception e) {
              return 'Label Not Found';
          }
    }
}